### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by xFlyingJonasx** [sddsd2332/MEK-1.12.2-v10#28]
There is at least one visiual bug, by the other one I'm not sure if it was planned.

The first visual bug is that the speed and energy upgrade text are coming out of the black area.
https://user-images.githubusercontent.com/108744081/233703681-f792b2fc-3c23-4c62-8a0d-46bf6a813d4c.png

The second (visual bug) is that those ultimate machine names getting written together without any space.
https://user-images.githubusercontent.com/108744081/233704423-8ed7ee98-4cd6-4b0f-818b-99d3a9a1b6c9.png

**Comment by sddsd2332** [comment]
> There is at least one visiual bug, by the other one I'm not sure if it was planned.
> 
> The first visual bug is that the speed and energy upgrade text are coming out of the black area. https://user-images.githubusercontent.com/108744081/233703681-f792b2fc-3c23-4c62-8a0d-46bf6a813d4c.png

emm
This may be due to me trying to change the language height [because it looks good in Chinese [Simplified]]
If that I would adjust the larger GUI or change the display back [use the configuration file to adjust]

> The second (visual bug) is that those ultimate machine names getting written together without any space. https://user-images.githubusercontent.com/108744081/233704423-8ed7ee98-4cd6-4b0f-818b-99d3a9a1b6c9.png

This is the same as the high version of mekanism [kind of forgot how it is displayed]
Again, this will be modified or adjusted using a configuration file
